### Initialize Data
POST http://localhost:8080/admin/data


### Catalog
GET http://localhost:8080/catalog

### Authors
GET http://localhost:8080/authors

###
POST http://localhost:8080/orders
Content-Type: application/json

{
  "items": [
    {
      "bookId": 89,
      "quantity": 1
    },
    {
      "bookId": 12,
      "quantity": 2
    }
  ],
  "recipient": {
    "name": "John Doe",
    "phone": "123-456-789",
    "street": "Cwiartki 3/4",
    "city": "Krakow",
    "zipCode": "30-150",
    "email": "johndoe@example.org"
  }
}

###
GET http://localhost:8080/orders/115

###
GET http://localhost:8080/uploads/90/file

###
PUT http://localhost:8080/orders/16/status
Content-Type: application/json

{
  "status": "CANCELED"
}