### Initialize Data
POST http://localhost:8080/admin/data


### Catalog
GET http://localhost:8080/catalog

###
POST http://localhost:8080/orders
Content-Type: application/json

{
  "items": [
    {
      "bookId": 3,
      "quantity": 1
    },
    {
      "bookId": 4,
      "quantity": 2
    }
  ],
  "recipient": {
    "name": "John Doe",
    "phone": "123-456-789",
    "street": "Cwiartki 3/4",
    "city": "Krakow",
    "zipCode": "30-150",
    "email": "johndoe@example.org"
  }
}

###
GET http://localhost:8080/orders


###
PUT http://localhost:8080/orders/9/status
Content-Type: application/json

{
  "status": "SHIPPED"
}