// @no-redirect
POST localhost:8080/login
Content-Type: application/json

{
  "username": "admin",
  "password": "xxx"
}

### orders
GET localhost:8080/catalog


### registration
POST localhost:8080/users
Content-Type: application/json

{
  "username": "darek@example.org",
  "password": "xxx"
}

### login

// @no-redirect
POST localhost:8080/login
Content-Type: application/json

{
"username": "darek@example.org",
"password": "xxx"
}